Feat/calcular lucro
NandaDuarte/koru-mobile-projeto-3 pull request #12
Opened 2024-04-09 16:35 UTC by adevalter

Boa tarde ! 
Implementado os dois Métodos 
Classe Cliente - verProdutosComprados
Classe Revendedor - calcularLucro

2024-04-09 16:58 UTC, meikahime approved these changes

2024-04-09 18:42 UTC, viniciusmatoso requested changes
remover o arquivo "launch.json" no .vscode

2024-04-09 21:27 UTC, viniciusmatoso approved these changes

2024-04-09 21:53 UTC, josiasjunior716 approved these changes

2024-04-10 11:54 UTC, merged

2024-04-10 11:55 UTC, NandaDuarte approved these changes