feat:Implementação do try/catch
NandaDuarte/koru-mobile-projeto-3 pull request #13
Opened 2024-04-10 03:18 UTC by Dani-Souza

Implementação do try/cath em método comprar produto, para teste foi forçado erro com throw.
![image](https://github.com/NandaDuarte/koru-mobile-projeto-3/assets/161641299/eedfe09e-893c-4a0d-af7f-2074961a73bf)

2024-04-10 03:44 UTC, viniciusmatoso approved these changes

2024-04-10 11:51 UTC, adevalter requested changes
Você deve colocar o try antes do if e no else você adiciona o throw ("com a mensagem de erro") que assim ele ira chamar o catch

2024-04-11 15:21 UTC, adevalter approved these changes
ok aprovado

2024-04-12 00:49 UTC, NandaDuarte approved these changes

2024-04-12 00:49 UTC, merged