Feat/metodototalemediaprd
NandaDuarte/koru-mobile-projeto-3 pull request #18
Opened 2024-04-12 02:24 UTC by NandaDuarte

Implementado as duas tarefas
metodo calcular total vendido
metodo calcular media produto vendido

2024-04-12 02:51 UTC, viniciusmatoso approved these changes

2024-04-12 16:58 UTC, adevalter approved these changes
Aprovado

2024-04-12 20:27 UTC, Dani-Souza approved these changes

2024-04-13 02:47 UTC, Dani-Souza commented on classes/revendedor.dart
> +  }
onde será usado esse método que sempre retornará zero?

2024-04-13 02:56 UTC, Dani-Souza commented on main.dart
> +print("a media do produto vendido é: ${func1.calcularMediaProdutosVendidos()}");
Essa implementação dos prints é de outra tarefa, não é necessário nesse Pr.

2024-04-13 03:02 UTC, Dani-Souza requested changes

2024-04-13 03:02 UTC, Dani-Souza commented on classes/revendedor.dart
> +    return this.calcularTotalProdutosVendidos() / this.produtosVendidos.length;
seria interessante colocar um try/catch igual foi feito no método `calcularLucro`
```
double calcularMediaProdutosVendidos(){
   try {
         return this.calcularTotalProdutosVendidos() / this.produtosVendidos.length;
       } catch (e) {
         return 0.00;
       }
    }
```

2024-04-16 02:32 UTC, Dani-Souza approved these changes

2024-04-16 02:33 UTC, merged